# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'K-lab-project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for K-lab-project
pod 'GoogleSignIn'
pod 'GoogleSignInSwiftSupport'
pod 'SwiftSocket'

end
